server:
  port: 8080

spring:
  application:
    name: bookti
  profiles:
    active: dev
  sql:
    init:
      mode: always
  jpa:
    show-sql: false
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format-sql: true
  datasource:
    driverClassName: ${DRIVER_CLASS_NAME}
    url: jdbc:postgresql://localhost:5432/bookti
    username: postgres
    password: password
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${GMAIL_USERNAME}
    password: ${GMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

frontend-url: ${FRONTEND_URL}

jwt:
  access-token:
    private: ${ACCESS_TOKEN_PRIVATE_KEY_PATH}
    public: ${ACCESS_TOKEN_PUBLIC_KEY_PATH}
  refresh-token:
    private: ${REFRESH_TOKEN_PRIVATE_KEY_PATH}
    public: ${REFRESH_TOKEN_PUBLIC_KEY_PATH}

application:
  permit-all-req:
    - /v2/api-docs/**
    - /v3/api-docs/**
    - /swagger-resources/**
    - /configuration/**
    - /webjars/**
    - /swagger-ui/*
    - /swagger-ui.html
    - /api/v1/authorize/**

logging:
  level:
    root: INFO
    org.springframework.security: INFO
