ACCESS_TOKEN_PRIVATE_KEY_PATH: "access-refresh-token-keys/access-token-private.key"
ACCESS_TOKEN_PUBLIC_KEY_PATH: "access-refresh-token-keys/access-token-public.key"
REFRESH_TOKEN_PRIVATE_KEY_PATH: "access-refresh-token-keys/refresh-token-private.key"
REFRESH_TOKEN_PUBLIC_KEY_PATH: "access-refresh-token-keys/refresh-token-public.key"
DRIVER_CLASS_NAME: org.postgresql.Driver
DB_URL: postgresql://localhost:5432/bookti
DB_USERNAME: postgres
DB_PASSWORD: unit1234
FRONTEND_URL: https://marketplace-bookti.vercel.app
