name: Checkstyle

on:
  push:
    branches: [ "main", "development" ]
  pull_request:
    branches: [ "main", "development" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Checkstyle for Java
        uses: dbelyaev/action-checkstyle@v1.2.1
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-check
          checkstyle_config: checkstyle.xml
          level: warning
          workdir: 'src/main/java'